server.port: 8082

---

spring:
  profiles:
    active: test
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/crap-advisor
    username: postgres
    password: postgres
logging:
  level:
    com.aiecel.crapadvisor: debug